version: '2'
services:
  minio:
    image: 'bitnami/minio:2020.2.20'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
